version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:27"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 3
