const normalize = value => String(value || '')
  .toLowerCase()
  .replace(/æ/g, 'ae')
  .replace(/ø/g, 'o')
  .replace(/å/g, 'aa')
  .normalize('NFKD')
  .replace(/[\u0300-\u036f]/g, '')
  .replace(/[^a-z0-9]+/g, ' ')
  .trim();

const title = (pattern, nameZh) => [pattern, nameZh];

const DANISH_PRODUCT_FORM_TITLES = [
  title(/sagra.*butchers.*poussin/, 'Butterfly 童子鸡或黄皮童子鸡任选'),
  title(/dansk kalve flanksteak/, '丹麦小牛腹肉排（原味或腌制）'),
  title(/danske svinekoteletter/, '丹麦猪排（原味或腌制）'),
  title(/filet ala morbrad.*polser/, '调味猪里脊式肉排或多种香肠任选'),
  title(/koteletter.*grillsticks.*grillpolser/, '猪排、烧烤肉条或烧烤肠任选'),
  title(/mutti.*tomater.*pizzasauce/, 'Mutti 番茄罐头或披萨酱任选'),
  title(/nektariner.*ferskner.*blommer.*abrikoser/, '油桃、桃子、李子或杏任选'),
  title(/marinerede.*grillspyd.*lamm/, '腌制羊肉烧烤串'),
  title(/marinerede.*flanksteak/, '腌制牛腹肉排'),
  title(/bacontern/, '培根丁'),
  title(/skinkestrimler/, '火腿条'),
  title(/serranoskinke/, '西班牙塞拉诺风干火腿'),
  title(/skinke i skiver/, '切片火腿'),
  title(/grill.*pande.*wiener.*hotdogpolser/, '煎烤肠、维也纳肠或热狗肠任选'),
  title(/pizzasauce/, '披萨酱'),
  title(/kania.*chilisauce/, 'KANIA 辣椒酱'),
  title(/sursod.*foraarsrullesauce/, '糖醋酱或春卷蘸酱任选'),
  title(/vitasia.*woksauce/, 'VITASIA 炒菜酱'),
  title(/lambi classic papir/, 'Lambi 卫生纸或厨房纸任选'),
  title(/godt papir/, '卫生纸或厨房纸任选'),
  title(/paalaegsbokse/, '冷切食品收纳盒'),
  title(/citronella.*lys/, '香茅驱蚊蜡烛'),
  title(/frikadeller.*fiskefilet.*kamsteg/, '丹麦肉饼、炸鱼柳或烤猪肉片任选'),
  title(/morbrad.*kartoffel.*kyllingebryst.*flodekartof/, '猪里脊配土豆塔或奶酪鸡胸配奶油土豆任选'),
  title(/burnt ends.*hakket oksekod/, 'BBQ 熟牛肉块或牛肉末任选'),
  title(/shampoo.*balsam.*skifteunderlag/, '洗护用品或婴儿换尿垫任选'),
  title(/knorr.*pasta.*risretter.*hellmanns.*maille/, '方便意面/米饭、蛋黄酱或芥末酱任选'),
  title(/naturli.*smorbar.*iskaffe.*havre.*mandel.*drik/, '植物抹酱、冰咖啡或植物饮任选'),
  title(/burger boost/, 'Burger Boost 牛肉汉堡饼'),
  title(/vita d or.*solsikke.*rapsolie/, '葵花籽油或菜籽油任选'),
  title(/crosti.*basilikum.*hvidlog/, '罗勒蒜味烤面包脆片'),
  title(/maelkesnitter/, '牛奶夹心蛋糕'),
  title(/sol mar.*blaeksprutte.*chorizo/, '鱿鱼圈或 Chorizo 辣肠可乐饼任选'),
  title(/chef select.*kyllingenuggets/, 'PAW Patrol 造型裹粉鸡块'),
  title(/danpo tempura nuggets.*cordon bleu/, '天妇罗鸡块或鸡肉蓝带肉排任选'),
  title(/cordon bleu af fjerkrae/, '禽肉蓝带夹心肉排'),
  title(/kyllingeburger/, '裹粉鸡肉汉堡饼'),
  title(/ribsteak.*bbq/, 'BBQ 腌制猪肋排肉片'),
  title(/marineret morbrad.*gris/, '腌制猪里脊'),
  title(/marineret oksecuvette/, '腌制牛后臀尖肉'),
  title(/salsiccia/, '意式 Salsiccia 烧烤香肠'),
  title(/4 burgerboller.*6 polsebrod/, '4 个汉堡面包或 6 个热狗面包'),
  title(/tandpasta.*tandborster.*mundskyl/, '牙膏、牙刷或漱口水任选'),
  title(/pasteis de nata/, '葡式蛋挞'),
  title(/churros/, '西班牙吉事果'),
  title(/magdalenas/, '西班牙玛德琳小蛋糕'),
  title(/wienerstang/, '丹麦酥皮长条甜点'),
  title(/fransk hotdog/, '法式热狗'),
  title(/kyllingebryst.*laar|laar.*kyllingebryst/, '鸡胸肉或鸡腿肉任选'),
  title(/tomatkniv/, '番茄刀套装'),
  title(/tomatkonserves/, '番茄罐头'),
  title(/tomatpure.*pastasauce/, '番茄膏或意面酱'),
  title(/tomat ketchup.*sauce|tomatketchup.*sauce/, '番茄酱或烹调酱'),
  title(/\bketchup\b/, '番茄酱'),
  title(/opvaskemiddel/, '洗碗液'),
  title(/maskinopvask/, '洗碗机洗涤剂'),
  title(/jordbaer.*vaniljeis|vaniljeis.*jordbaer/, '草莓或香草冰淇淋'),
  title(/\bis\b|ispind|isvafler|isbaeger|iskasse|gelato|gelatelli/, '冰淇淋或冰品'),
  title(/sandwich kiks|\bkiks\b|smaakager|cookies|vafler/, '饼干或华夫点心'),
  title(/jordbaertaerte/, '草莓挞'),
  title(/jordbaerkage/, '草莓蛋糕'),
  title(/granola|musli|mysli|muesli|crusli|cruesli|havregryn|morgenmad/, '早餐谷物或燕麦'),
  title(/paalaegschokolade/, '面包用薄片巧克力'),
  title(/frugtpaalaeg|grinebidder/, '水果条/水果片零食'),
  title(/rejeost|skinkeost/, '虾味或火腿味奶油奶酪'),
  title(/mexitopping/, '墨西哥菜用刨丝奶酪'),
  title(/halloumi|grillost/, '哈罗米烧烤奶酪'),
  title(/feta|hvid ost/, '菲达式白奶酪'),
  title(/osteplatte/, '奶酪拼盘'),
  title(/friskost/, '新鲜奶油奶酪'),
  title(/smorcroissant/, '冷冻黄油可颂'),
  title(/smorrebrod/, '丹麦开放式三明治'),
  title(/paalaegssalat/, '三明治夹馅沙拉/抹酱'),
  title(/forarsruller|spring rolls|miniruller/, '冷冻春卷'),
  title(/asia cubes/, '冷冻亚洲风味小食'),
];

// These phrases are deliberately product-form first. They are maintained by
// Codex and materialized into the repository; the website never calls an AI or
// translation API at runtime.
const DANISH_TITLES = [
  title(/paalaegschokolade/, '面包用薄片巧克力'),
  title(/frugtpaalaeg|grinebidder/, '水果条/水果片零食'),
  title(/rejeost|skinkeost/, '虾味或火腿味奶油奶酪'),
  title(/smorcroissant/, '冷冻黄油可颂'),
  title(/smorrebrod/, '丹麦开放式三明治'),
  title(/burgerboller/, '汉堡面包胚'),
  title(/polsebrod|hotdogbrod/, '热狗面包'),
  title(/kyllingepopcorn/, '爆米花鸡块（裹粉小鸡块）'),
  title(/morliny.*classic.*crispy hot wings/, 'Morliny 原味或香辣脆皮鸡翅'),
  title(/kyllingeburger.*nuggets?/, '鸡肉汉堡饼或鸡块'),
  title(/kyllingespyd/, '调味鸡肉串'),
  title(/kyllingevinger/, '鸡翅'),
  title(/hot ?wings|buffalo wings|\bwings\b/, '调味鸡翅'),
  title(/kalkunoverlaar.*schnitzel.*bryst/, '火鸡大腿或火鸡胸薄片任选'),
  title(/paalaeg.*postej.*kalkunbacon/, '冷切、肝酱或火鸡培根任选'),
  title(/kalkunhakkebof/, '火鸡肉饼'),
  title(/cordon bleu.*kalkun/, '火鸡蓝带肉排'),
  title(/kalkunbryst/, '火鸡胸肉'),
  title(/kalkunoverlaar/, '火鸡大腿'),
  title(/kalkununderlaar/, '火鸡小腿'),
  title(/kalkunschnitz/, '火鸡胸薄片'),
  title(/kalkunstrimler/, '火鸡胸肉条'),
  title(/hakket kalkun/, '火鸡肉末'),
  title(/poussin/, '童子鸡'),
  title(/kyllingebryst.*inderfilet|inderfilet.*kylling/, '鸡胸肉或鸡里脊'),
  title(/kyllingebryst/, '鸡胸肉'),
  title(/kyllingeoverlaar|udbenede.*overlaar/, '鸡大腿肉'),
  title(/kyllingeunderlaar/, '鸡小腿'),
  title(/kyllingelaar|hele.*laar/, '整只鸡腿'),
  title(/hakket kylling/, '鸡肉末'),
  title(/hel kylling/, '整只鸡'),
  title(/kyllingemarked/, '多款鸡肉任选'),
  title(/fransk majskylling/, '法国玉米饲养鸡'),
  title(/kylling snack polser/, '鸡肉零食香肠'),
  title(/kyllingepolser/, '鸡肉香肠'),
  title(/grisemorbrad|moerbrad.*gris/, '猪里脊'),
  title(/flaeskesteg|ovnklar.*steg/, '丹麦脆皮烤猪肉块'),
  title(/ribbensteg/, '带皮猪肋烤肉'),
  title(/porchetta/, '意式香草烤猪肉卷'),
  title(/pulled pork/, '手撕猪肉'),
  title(/spareribs|long ribs/, '猪肋排'),
  title(/kamben/, '猪肋骨'),
  title(/nakkekotelet/, '猪梅花肉排'),
  title(/kamkotelet/, '猪里脊排'),
  title(/kotelet/, '猪排'),
  title(/stegeflaesk|flaesk i skiver/, '切片猪五花肉'),
  title(/hakket gris.*kalv|hakket kalv.*gris/, '猪肉与小牛肉混合肉末'),
  title(/hakket gris/, '猪肉末'),
  title(/frikadeller/, '丹麦肉丸饼'),
  title(/kodbol/, '肉丸'),
  title(/farsbrod/, '肉糜烤肉卷'),
  title(/bacon.*strimler/, '培根条'),
  title(/bacon.*skiver/, '培根片'),
  title(/\bbacon\b/, '培根'),
  title(/hamburgerryg/, '烟熏猪里脊冷切'),
  title(/leverpostej|\bpostej\b/, '丹麦肝酱'),
  title(/spegepolse|salami/, '萨拉米或风干香肠'),
  title(/chorizo/, '西班牙辣味香肠'),
  title(/medister/, '丹麦粗猪肉香肠'),
  title(/frankfurter/, '法兰克福香肠'),
  title(/bockwurst/, '德式博克香肠'),
  title(/krakauer|krainer/, '中欧烟熏香肠'),
  title(/grillpolser|\bpolser\b/, '烧烤香肠'),
  title(/italiensk paalaeg/, '意式冷切肉'),
  title(/\bpaalaeg\b/, '三明治冷切或抹酱'),

  title(/hakket okse.*gris|hakket gris.*okse/, '牛猪混合肉末'),
  title(/hakket okse/, '牛肉末'),
  title(/burgerboffer|hamburger af oksekod/, '牛肉汉堡饼'),
  title(/oksekod i tern/, '牛肉丁'),
  title(/oksekod i strimler/, '牛肉条'),
  title(/rumpsteak.*entrecote|entrecote.*rumpsteak/, '牛臀排或肋眼牛排'),
  title(/striploin.*ribeye roast|ribeye roast.*striploin/, '西冷或肋眼整块烤牛肉'),
  title(/striploin.*ribeye.*rumpsteak|rumpsteak.*ribeye.*striploin/, '西冷、肋眼或牛臀排'),
  title(/ribeye|rib eye/, '肋眼牛排'),
  title(/entrecote/, '西冷肋眼牛排'),
  title(/rumpsteak/, '牛臀排'),
  title(/flatsteak|flanksteak/, '牛腹肉排'),
  title(/culotte/, '牛臀尖烤肉'),
  title(/roastbeef/, '烤牛肉'),
  title(/striploin/, '纽约客/外脊牛排'),
  title(/tykstegsboffer/, '牛臀肉排'),
  title(/kalvesteak|kalvemarked/, '小牛肉或小牛排'),
  title(/oksesteak|\bsteak/, '牛排'),
  title(/lammeculotte/, '羊臀尖烤肉'),
  title(/lamme/, '羊肉'),

  title(/koldroget.*laks/, '冷熏三文鱼'),
  title(/varmroget.*laks/, '热熏三文鱼'),
  title(/roget.*laks|gravad.*laks/, '烟熏或腌渍三文鱼'),
  title(/hel laksefilet/, '整片带皮三文鱼柳'),
  title(/laksefilet|laksestykke/, '三文鱼柳'),
  title(/gronlandsrejer/, '格陵兰冷水虾'),
  title(/vannameirejer/, '南美白虾'),
  title(/kaemperejer|gambas/, '大虾'),
  title(/rejer i lage/, '盐水浸虾仁'),
  title(/torpedo rejer/, '裹粉蝴蝶虾'),
  title(/fiskepinde/, '裹粉鱼条'),
  title(/fiskefrikadeller/, '丹麦鱼肉饼'),
  title(/fiskefars/, '调味鱼肉糜'),
  title(/tunsteak/, '金枪鱼排'),
  title(/\btun\b/, '金枪鱼罐头或鱼排'),
  title(/torskefileter/, '鳕鱼柳'),
  title(/rodspaette/, '鲽鱼'),
  title(/makrel/, '鲭鱼'),
  title(/sardiner/, '沙丁鱼'),
  title(/dorade/, '金头鲷'),
  title(/blaeksprutteringe/, '鱿鱼圈'),
  title(/skagensalat/, '丹麦虾肉沙拉酱'),
  title(/fiskemarked|seafoodmix|skaldyrsmarked/, '多款鱼类或海鲜任选'),

  title(/rejeost|skinkeost/, '虾味或火腿味奶油奶酪'),
  title(/blaaskimmelost/, '蓝纹奶酪'),
  title(/flodeost/, '奶油奶酪'),
  title(/smelteost/, '加工融化奶酪'),
  title(/smoreost|smorbar ost/, '涂抹奶酪'),
  title(/hytteost/, '茅屋奶酪'),
  title(/revet mozzarella/, '刨丝马苏里拉奶酪'),
  title(/mozzarella/, '马苏里拉奶酪'),
  title(/grana padano|parmesan/, '帕达诺/帕玛森硬质奶酪'),
  title(/havarti/, '哈瓦蒂奶酪'),
  title(/danbo/, '丹麦 Danbo 奶酪'),
  title(/gouda.*cheddar|cheddar.*gouda/, '高达或切达奶酪'),
  title(/gouda/, '高达奶酪'),
  title(/cheddar/, '切达奶酪'),
  title(/skiveost/, '切片奶酪'),
  title(/skaereost/, '块状切片奶酪'),
  title(/salatost/, '沙拉白奶酪'),
  title(/\bost\b/, '奶酪'),
  title(/graesk yoghurt/, '希腊酸奶'),
  title(/drikkeyoghurt/, '饮用酸奶'),
  title(/\byoghurt\b/, '酸奶'),
  title(/\bskyr\b/, 'Skyr 高蛋白发酵乳'),
  title(/\bkefir\b/, '开菲尔发酵乳'),
  title(/\ba38\b/, 'A38 丹麦酸牛奶'),
  title(/koldskaal/, '丹麦冷甜酸奶汤'),
  title(/piskeflode/, '淡奶油/打发奶油'),
  title(/madlavningsflode/, '烹饪奶油'),
  title(/creme fraiche|\bfraiche\b/, '酸奶油'),
  title(/kakaomaelk/, '巧克力牛奶'),
  title(/kaernemaelk/, '酪乳'),
  title(/protein ?drik|proteinshake/, '蛋白乳饮料'),
  title(/laktosefri maelk/, '无乳糖牛奶'),
  title(/havredrik/, '燕麦饮'),
  title(/sojadrik/, '豆奶'),
  title(/skrabeaeg/, '平养鸡蛋'),
  title(/frilandsaeg/, '散养鸡蛋'),
  title(/okologiske aeg/, '有机鸡蛋'),
  title(/\baeg\b/, '鸡蛋'),
  title(/smorcroissant/, '冷冻黄油可颂'),
  title(/smorrebrod/, '丹麦开放式三明治'),
  title(/\bsmor\b|smorbar/, '黄油或涂抹黄油'),
  title(/margarine/, '人造黄油'),

  title(/purlog/, '细香葱'),
  title(/basilikum/, '罗勒'),
  title(/persille/, '欧芹'),
  title(/gulerod/, '胡萝卜'),
  title(/broccoli/, '西兰花'),
  title(/blomkaal/, '花椰菜'),
  title(/spidskaal/, '尖头卷心菜'),
  title(/bananer?/, '香蕉'),
  title(/hvidkaalssalat/, '卷心菜沙拉'),
  title(/icebergsalat/, '冰山生菜'),
  title(/hjertesalat/, '小颗罗马生菜'),
  title(/spinat/, '菠菜'),
  title(/champignon/, '口蘑/白蘑菇'),
  title(/snacktomat/, '小番茄'),
  title(/blommetomat/, '李形番茄'),
  title(/cocktailtomat/, '鸡尾酒番茄'),
  title(/tomater? paa stilk|stilktomat/, '带藤番茄'),
  title(/\btomat/, '番茄'),
  title(/snackpeber/, '甜味小彩椒'),
  title(/rod peber/, '红甜椒'),
  title(/agurk/, '黄瓜'),
  title(/majs(?:kolber?|kolbe)/, '鲜玉米棒'),
  title(/\bmajs\b/, '玉米'),
  title(/danske lose aerter/, '丹麦带荚鲜豌豆'),
  title(/\baerter\b/, '豌豆'),
  title(/kartoffelsalat/, '土豆沙拉'),
  title(/bagekartofler/, '烘烤用大土豆'),
  title(/nye.*kartofler/, '新季小土豆'),
  title(/grydeklare kartofler/, '已清洗可直接烹调的土豆'),
  title(/\bkartofler\b/, '新鲜土豆'),
  title(/pommes frites/, '冷冻薯条'),
  title(/kartoffelbaade/, '冷冻薯角'),
  title(/kartoffelkroket/, '土豆可乐饼'),
  title(/kartoffelgratin|flodekartof/, '奶油焗土豆'),
  title(/kartoffelrosti/, '瑞士土豆饼'),

  title(/jordbaer/, '草莓'),
  title(/blaabaer/, '蓝莓'),
  title(/solbaer/, '黑加仑'),
  title(/vandmelon/, '西瓜'),
  title(/honningmelon/, '蜜瓜'),
  title(/kantalup|cantaloupe/, '网纹甜瓜'),
  title(/vindruer|\bdruer\b/, '葡萄'),
  title(/nektarin.*fersken|fersken.*nektarin/, '桃或油桃'),
  title(/nektarin/, '油桃'),
  title(/fersken/, '桃子'),
  title(/sveskeblommer/, '西梅李'),
  title(/\bblomme\b/, '李子'),
  title(/abrikoser/, '杏'),
  title(/kirsebaer/, '樱桃'),
  title(/pink lady.*aebler/, 'Pink Lady 苹果'),
  title(/\baebler\b/, '苹果'),
  title(/mango/, '芒果'),
  title(/avocado/, '牛油果'),
  title(/ananas/, '菠萝'),
  title(/melonmix|frugtmix/, '切配水果拼盘'),

  title(/forarsruller|spring rolls|miniruller/, '冷冻春卷'),
  title(/asia cubes/, '冷冻亚洲风味小食'),
  title(/pierogi|pelmeni|wareniki/, '东欧馅饺'),
  title(/kartoffel dumplings/, '土豆团子'),
  title(/\bdumplings\b/, '冷冻饺子'),
  title(/\bpizza\b/, '冷冻或即食披萨'),
  title(/lasagne|lasagnette/, '千层面方便餐'),
  title(/biksemad/, '丹麦土豆肉丁杂烩'),
  title(/bami goreng/, '印尼炒面方便餐'),
  title(/borsjtj/, '东欧甜菜根汤'),
  title(/pokebowl/, '夏威夷风味盖饭碗'),
  title(/panini/, '帕尼尼热压三明治'),
  title(/falafel/, '炸鹰嘴豆丸'),
  title(/faerdigret/, '预制方便餐'),
  title(/ispind/, '冰棒'),
  title(/isvafler/, '蛋筒冰淇淋'),
  title(/sandwichis/, '冰淇淋三明治'),
  title(/mochi/, '麻薯冰淇淋'),
  title(/isbaeger/, '杯装冰淇淋'),
  title(/\bis\b|gelato|gelatelli/, '冰淇淋'),

  title(/rugbrod/, '丹麦黑麦面包'),
  title(/fladbrod/, '扁面包'),
  title(/schwarzbrod/, '德式深色黑麦面包'),
  title(/fodselsdagsboller/, '丹麦生日甜面包'),
  title(/fuldkornskrydderboller/, '全麦香料小面包'),
  title(/burgerboller/, '汉堡面包胚'),
  title(/polsebrod|hotdogbrod/, '热狗面包'),
  title(/rundstykker/, '丹麦早餐小圆面包'),
  title(/baguette|flutes/, '法棍面包'),
  title(/pitabrod/, '皮塔饼'),
  title(/focaccia/, '佛卡夏面包'),
  title(/ciabatta/, '恰巴塔面包'),
  title(/brioche/, '布里欧修黄油面包'),
  title(/kanelsnegl/, '肉桂卷'),
  title(/\bbrod\b/, '面包'),
  title(/spaghetti/, '意大利细面'),
  title(/lasagneplader/, '千层面片'),
  title(/aegnudler/, '鸡蛋面'),
  title(/cup noodles|kopnudler/, '杯装方便面'),
  title(/nudler|noodles/, '面条或方便面'),
  title(/gnocchi/, '意式土豆团子'),
  title(/pasta/, '意大利面'),
  title(/jasminris/, '茉莉香米'),
  title(/basmati/, '印度香米'),
  title(/\bris\b/, '大米'),
  title(/tortilla|wraps/, '墨西哥卷饼皮'),
  title(/filodej/, '菲洛薄酥皮'),
  title(/pizzamel|tipo 00/, '披萨用 00 号面粉'),
  title(/\bmel\b/, '面粉'),

  title(/granola|musli|mysli|muesli|crusli/, '什锦早餐谷物'),
  title(/havregryn/, '燕麦片'),
  title(/morgenmad/, '早餐谷物'),
  title(/\bgrod\b/, '即食粥'),
  title(/instant kaffe/, '速溶咖啡'),
  title(/hele kaffebonner|helbonner/, '整粒咖啡豆'),
  title(/formalet kaffe/, '研磨咖啡粉'),
  title(/iskaffe/, '冰咖啡饮料'),
  title(/kaffe/, '咖啡'),
  title(/marmelade/, '果酱'),
  title(/peanutbutter/, '花生酱'),
  title(/nutella/, '榛子巧克力酱'),
  title(/honning/, '蜂蜜'),

  title(/hakkede tomater|tomatkonserves/, '番茄罐头'),
  title(/kikaerter/, '鹰嘴豆'),
  title(/\bbonner\b/, '豆类罐头'),
  title(/kokosmaelk/, '椰奶罐头'),
  title(/ketchup/, '番茄酱'),
  title(/mayonnaise/, '蛋黄酱'),
  title(/remoulade/, '丹麦酸黄瓜蛋黄酱'),
  title(/sennep/, '芥末酱'),
  title(/dressing/, '沙拉酱'),
  title(/bearnaise/, '贝阿恩酱'),
  title(/pesto/, '青酱'),
  title(/hummus/, '鹰嘴豆泥'),
  title(/\bsauce\b/, '烹调酱料'),
  title(/olivenolie/, '特级初榨橄榄油'),
  title(/bouillon|\bfond\b/, '高汤块或浓缩高汤'),
  title(/krydderi/, '混合香料'),
  title(/ristede log/, '炸洋葱酥'),
  title(/\bsesam\b/, '芝麻'),
  title(/vaniljesukker/, '香草糖'),
  title(/rorsukker/, '蔗糖'),
  title(/\bsukker\b/, '白砂糖'),
  title(/syltede agurker/, '腌黄瓜'),
  title(/syltede rodlog/, '腌红洋葱'),
  title(/sauerkraut/, '德式酸菜'),
  title(/\boliven\b/, '橄榄'),
  title(/ajvar|pindur/, '巴尔干烤椒酱'),

  title(/paalaegschokolade/, '面包用薄片巧克力'),
  title(/frugtpaalaeg|grinebidder/, '水果条/水果片零食'),
  title(/bananchips/, '香蕉片'),
  title(/mikrobolgeovns popcorn/, '微波炉爆米花'),
  title(/\bpopcorn\b/, '爆米花'),
  title(/pretzels/, '椒盐脆饼'),
  title(/\bchips\b|doritos|bugles/, '薯片或玉米脆片'),
  title(/cashewnodder/, '腰果'),
  title(/valnodder/, '核桃'),
  title(/pistacienodder/, '开心果'),
  title(/mandler/, '杏仁'),
  title(/peanuts|jordnodder/, '花生'),
  title(/noddeblanding|noddemix/, '混合坚果'),
  title(/rosiner/, '葡萄干'),
  title(/svesker/, '西梅干'),
  title(/torrede tranebaer/, '蔓越莓干'),
  title(/frysetor/, '冻干水果'),
  title(/pandekage/, '煎饼或煎饼粉'),
  title(/majskiks/, '玉米米饼'),
  title(/kammerjunkere/, '丹麦脆小饼干'),
  title(/kanelgifler/, '迷你肉桂卷'),
  title(/jordbaertaerte/, '草莓挞'),
  title(/lagkage/, '夹层奶油蛋糕'),
  title(/kanelsnegl/, '肉桂卷'),
  title(/småkager|smaakager|\bkiks\b|cookies/, '饼干'),
  title(/donut/, '甜甜圈'),
  title(/\bkage\b/, '蛋糕'),
  title(/proteinbar/, '蛋白棒'),
  title(/flodeboller/, '巧克力包裹蛋白霜甜点'),
  title(/bolcher/, '硬糖'),
  title(/familieposer/, '家庭装混合糖果'),
  title(/mentos/, '曼妥思薄荷糖/水果糖'),
  title(/sesambar/, '芝麻糖棒'),
  title(/chokolade/, '巧克力'),
  title(/slikpose|\bslik\b/, '糖果'),

  title(/vaskekapsler/, '洗衣凝珠'),
  title(/vaskemiddel/, '洗衣液或洗衣粉'),
  title(/skyllemiddel/, '衣物柔顺剂'),
  title(/maskinopvask/, '洗碗机洗涤剂'),
  title(/toiletrengoring/, '马桶清洁剂'),
  title(/rengoringsmiddel/, '家用清洁剂'),
  title(/affaldsposer/, '垃圾袋'),
  title(/fryseposer/, '食品冷冻袋'),
  title(/genluksposer/, '密封保鲜袋'),
  title(/toiletpapir/, '卫生纸'),
  title(/kokkenrulle/, '厨房纸'),
  title(/vaadservietter/, '湿巾'),
  title(/servietter/, '餐巾纸'),
  title(/bleer|buksebleer/, '婴儿纸尿裤/拉拉裤'),
  title(/babypleje/, '婴儿护理用品'),
  title(/babymad/, '婴幼儿辅食'),
  title(/grodpouch/, '袋装婴儿谷物粥'),
  title(/solcreme/, '防晒霜'),
  title(/aftersun/, '晒后修护乳'),
  title(/shampoo|balsam/, '洗发水或护发素'),
  title(/tandpasta|mundpleje/, '口腔护理用品'),
  title(/deodorant/, '止汗除味剂'),
  title(/hudpleje|serum|ansigtscreme/, '面部护肤品'),
  title(/kosttilskud|mae?lkesyrebakterier/, '益生菌或营养补充剂'),
  title(/cola|pepsi|fanta|sprite|sodavand/, '汽水或软饮'),
  title(/juice|smoothie|nektar/, '果汁或果味饮料'),
  title(/danskvand|mineralvand|kildevand/, '饮用水或气泡水'),
  title(/energidrik|energy drink/, '能量饮料'),
  title(/saft|ribena|opblanding/, '浓缩兑水饮料'),
  title(/\bol\b|beer|carlsberg|tuborg|heineken|corona/, '啤酒'),
  title(/vin|wine|prosecco|champagne|cava/, '葡萄酒或起泡酒'),
  title(/vodka|whisky|rom\b|gin\b|likor|snaps/, '烈酒或利口酒'),
  title(/cider|alcopop|ready to drink/, '苹果酒或即饮调制酒'),
  title(/kattemad|kattefoder|godbidder.*kat/, '猫粮或猫零食'),
  title(/hundemad|hundefoder|godbidder.*hund|strimler.*hund/, '狗粮或狗零食'),
  title(/led.*paere|paere.*led/, 'LED 灯泡'),
  title(/brodrister/, '烤面包机'),
  title(/kaffemaskine/, '咖啡机'),
  title(/gryde|kasserolle|stegepande/, '锅具'),
  title(/skoreol|opbevaring|reol/, '家居收纳用品'),
  title(/t shirt|troje|bukser|jakke/, '服装'),
  title(/blomster|buket/, '鲜花或花束'),
  title(/plante|potteplante/, '盆栽植物'),
  title(/legetoj|bamser?|spil/, '玩具或游戏'),
  title(/notesbog|kuglepen|blyant|kontorartikler/, '文具'),
  title(/cigaret|tobak/, '烟草制品'),
  title(/nikotin/, '尼古丁产品'),
];

const GROUP_DEFAULTS = {
  chicken_thigh: '鸡腿肉', chicken_breast: '鸡胸肉', whole_chicken: '整只鸡', chicken_minced: '鸡肉末',
  chicken_wings: '鸡翅', chicken_breaded: '裹粉鸡肉小食', chicken_skewers: '鸡肉串', chicken_sausages: '鸡肉香肠', chicken_mixed_offer: '多款鸡肉任选', chicken_other: '鸡肉商品',
  turkey_breast: '火鸡胸肉', turkey_thigh: '火鸡腿肉', turkey_minced: '火鸡肉末', turkey_processed: '火鸡加工肉品', turkey_mixed_offer: '多款火鸡部位任选', poultry_deli_mixed: '禽肉冷切多品项任选', other_poultry: '其他禽肉',
  pork_roast: '烤猪肉块', pork_tenderloin: '猪里脊', pork_ribs: '猪肋排', pork_chop: '猪排或猪肉片', pork_minced: '猪肉末', sausages: '香肠', bacon_deli: '肉类冷切', prepared_meatballs: '肉丸或肉糜制品', pork_mixed_offer: '多款猪肉任选', deli_spreads: '三明治夹馅沙拉/抹酱',
  beef_minced: '牛肉末', mixed_minced: '混合肉末', beef_ribeye: '肋眼牛排', beef_striploin: '外脊牛排', beef_flat_steak: '腹肉薄切牛排', beef_rump_steak: '牛臀排', beef_bone_steak: '带骨牛排', beef_steak: '其他牛排', beef_burgers: '牛肉汉堡饼', beef_diced: '牛肉丁或牛肉条', beef_roast: '整块烤牛肉', beef_deli: '牛肉熟食', beef_mixed_offer: '多款牛肉部位任选', prepared_beef_mixed_offer: '原味或腌制牛肉任选', mixed_meat_offer: '跨肉种多品项任选', lamb_other: '羊肉',
  salmon_fresh: '生鲜三文鱼', salmon_smoked: '烟熏或腌渍三文鱼', salmon: '三文鱼', shrimp: '虾', white_fish: '鱼类商品', seafood_mixed_offer: '多款鱼虾海鲜任选', seafood_other: '多款海鲜或加工海鲜', eggs: '鸡蛋', milk: '牛奶或乳饮料', plant_drinks: '植物奶', cream: '奶油', mixed_dairy: '多款乳制品任选', yoghurt: '酸奶或发酵乳', cheese: '奶酪',
  cheese_grated: '刨丝奶酪', cheese_sliced: '切片奶酪', cheese_spreadable: '涂抹奶酪', cheese_cottage_ricotta: '茅屋奶酪或 Ricotta', cheese_mozzarella_burrata: 'Mozzarella 或 Burrata', cheese_feta_white: 'Feta 或白奶酪', cheese_grilling: '煎烤奶酪', cheese_soft_mould: '软质或蓝纹奶酪', cheese_aged_hard: '熟成硬奶酪', cheese_danish_table: '丹麦餐桌奶酪', cheese_mixed_offer: '多款奶酪任选', cheese_other: '其他奶酪', butter: '黄油或涂抹脂',
  mushrooms: '蘑菇', cauliflower: '花椰菜', broccoli: '西兰花', lettuce: '生菜', spinach: '菠菜', chives: '细香葱', basil: '罗勒', parsley: '欧芹', mixed_fresh_herbs: '多款鲜香草任选', fresh_herbs: '鲜香草', carrots: '胡萝卜', root_vegetables: '根茎蔬菜', peppers: '甜椒或辣椒', peas: '豌豆', corn: '玉米', vegetable_mix: '蔬菜组合', mixed_produce: '多款果蔬任选', prepared_salad: '预制沙拉', potatoes_fresh: '新鲜土豆', potato_salad: '土豆沙拉', potato_sides: '加工土豆配菜', tomatoes: '番茄', cucumber: '黄瓜', cabbage: '卷心菜', onion_garlic: '葱姜蒜或洋葱', leafy_green: '叶菜', vegetables_other: '其他蔬菜',
  apples: '苹果', pears: '梨', strawberries: '草莓', blueberries: '蓝莓', other_berries: '莓果', watermelon: '西瓜', melon: '甜瓜', grapes: '葡萄', apricots: '杏', plums: '李子', cherries: '樱桃', peaches_nectarines: '桃或油桃', mixed_stone_fruit: '多款核果任选', pineapple: '菠萝', mango: '芒果', avocado: '牛油果', bananas: '香蕉', prepared_fruit: '切配水果', mixed_fruit: '多款水果任选',
  bread: '面包', mixed_bakery: '多款烘焙食品任选', rice: '大米', pasta_noodles: '意面或面条', flour_baking: '面粉或饼皮', pizza_snacks: '披萨', dumplings: '冷冻饺子或春卷', ready_meal: '预制方便餐', plant_based_meat: '植物肉或素香肠', frozen_vegetables: '冷冻蔬菜', ice_cream: '冰淇淋或冰品', cereal: '早餐谷物', coffee_tea: '咖啡或茶', spreads_jam: '果酱、蜂蜜或抹酱', mixed_grocery_offer: '跨类别食品任选', canned: '罐头食品', sauces: '酱料', spices: '香料或调味料', oil_vinegar: '食用油或醋', oil_mixed_offer: '多种食用油任选', baking_ingredients: '烘焙原料', pickled_vegetables: '腌菜或橄榄', chips: '咸味零食', chocolate: '巧克力或糖果', biscuits: '饼干或蛋糕', nuts: '坚果', dried_fruit: '果干',
  paper: '纸品', cleaning: '清洁用品', trash_bags: '垃圾袋或保鲜袋', kitchen_consumables: '厨房耗材', diapers: '纸尿裤', baby_care: '婴儿护理用品', baby_food: '婴幼儿食品', hair_body: '个人洗护用品', sun_care: '防晒用品', hygiene: '卫生护理用品', supplements: '营养补充剂', zero_soda: '无糖可乐或雪碧',
  drink_soda: '汽水或软饮', drink_juice: '果汁或果味饮料', drink_water: '饮用水或气泡水', drink_energy: '能量饮料', drink_sports: '运动饮料', drink_concentrate: '浓缩兑水饮料', drink_other: '其他饮料',
  alcohol_beer: '啤酒', alcohol_wine: '葡萄酒或起泡酒', alcohol_spirits: '烈酒或利口酒', alcohol_cider_rtd: '苹果酒或即饮调制酒', alcohol_other: '其他酒类',
  pet_cat: '猫粮或猫用品', pet_dog: '狗粮或狗用品', pet_other: '其他宠物用品', flower_bouquet: '鲜花或花束', plants: '盆栽或园艺植物',
  home_appliances: '家用小电器', home_cookware: '锅具或厨房工具', home_storage: '家居收纳用品', home_decor: '家居装饰用品', home_other: '其他家居用品',
  electronics_audio: '音频设备', electronics_computing: '数码产品或配件', electronics_lighting: '电子照明用品', electronics_other: '其他电子电器',
  clothing_adult: '成人服饰鞋袜', clothing_children: '儿童服饰鞋袜', clothing_other: '其他服饰配件', leisure_toys: '玩具或游戏', leisure_stationery: '文具用品', leisure_books: '图书或杂志', leisure_other: '其他休闲用品',
  tobacco_cigarettes: '烟草制品', tobacco_nicotine: '尼古丁产品', tobacco_other: '其他烟草相关商品', other_offer: '其他促销商品',
};

const ORIGINAL_NAME_FALLBACK_GROUPS = new Set([
  'drink_soda', 'drink_juice', 'drink_water', 'drink_energy', 'drink_sports', 'drink_concentrate', 'drink_other',
  'alcohol_beer', 'alcohol_wine', 'alcohol_spirits', 'alcohol_cider_rtd', 'alcohol_other',
  'pet_cat', 'pet_dog', 'pet_other', 'flower_bouquet', 'plants',
  'home_appliances', 'home_cookware', 'home_storage', 'home_decor', 'home_other',
  'electronics_audio', 'electronics_computing', 'electronics_lighting', 'electronics_other',
  'clothing_adult', 'clothing_children', 'clothing_other', 'leisure_toys', 'leisure_stationery', 'leisure_books', 'leisure_other',
  'tobacco_cigarettes', 'tobacco_nicotine', 'tobacco_other', 'other_offer',
]);

const SPECIFIC_DESCRIPTIONS = [
  [/filet ala morbrad.*polser/, '这是调味猪里脊式肉排，或法兰克福、普斯塔等多种香肠任选。均属于调味肉制品，但形态和烹调时间不同，购买时按包装选择。'],
  [/koteletter.*grillsticks.*grillpolser/, '这是猪排、烧烤肉条或烧烤肠任选，肉块与香肠形态不同；均需按包装说明彻底加热，并按想做的菜选择。'],
  [/mutti.*tomater.*pizzasauce/, '这是 Mutti 番茄罐头或披萨酱任选。番茄罐头适合炖菜、汤和意面，披萨酱可直接涂饼底；用途不同。'],
  [/nektariner.*ferskner.*blommer.*abrikoser/, '这是油桃、桃子、李子或杏任选，均为带核水果，可直接吃或做甜点；品种、成熟度和包装重量需按实际商品确认。'],
  [/frikadeller.*fiskefilet.*kamsteg/, '这是 3 个丹麦肉饼、3 片裹粉鱼柳或 3 片烤猪肉三选一的熟食促销。三种商品的肉种和用途不同，购买时按柜台标签确认。'],
  [/morbrad.*kartoffel.*kyllingebryst.*flodekartof/, '这是两款需加热的组合餐任选：猪里脊配土豆塔，或马苏里拉鸡胸配奶油土豆。它不是单独出售的生鲜猪肉或鸡胸。'],
  [/burnt ends.*hakket oksekod/, '这是 BBQ 熟制牛肉块或生牛肉末任选。前者加热即可配饭或夹面包，后者需彻底煮熟，可做肉酱、肉丸或汉堡。'],
  [/shampoo.*balsam.*skifteunderlag/, '促销选项横跨洗发/护发用品与婴儿一次性换尿垫；购买时必须按包装原名确认具体商品，不应把换尿垫理解为洗护液。'],
  [/knorr.*pasta.*risretter.*hellmanns.*maille/, '这是 Knorr 方便意面或米饭、Hellmann’s 蛋黄酱、Maille 芥末酱等跨类别任选促销。主食和酱料用途不同，购买时按包装原名确认。'],
  [/naturli.*smorbar.*iskaffe.*havre.*mandel.*drik/, '这是 Naturli 植物抹酱、冰咖啡、燕麦饮或杏仁饮任选。抹酱用于面包和烹饪，饮品可直接喝；需按包装确认具体一种。'],
  [/vita d or.*solsikke.*rapsolie/, '这是葵花籽油或菜籽油二选一，均可用于日常炒菜和烘焙；具体高温用途与容量按瓶身说明确认。'],
  [/sol mar.*blaeksprutte.*chorizo/, '这是裹粉鱿鱼圈或 Chorizo 西班牙辣肠可乐饼任选，通常需烤箱、空气炸锅或油炸加热；海鲜和肉类口味不同。'],
  [/crosti.*basilikum.*hvidlog/, '罗勒蒜味 Crosti 烤面包脆片，可直接当零食，也可配汤、沙拉或蘸酱；商品主体是烤面包，不是新鲜罗勒。'],
  [/maelkesnitter/, '牛奶奶油夹心小蛋糕，属于冷藏甜点，可直接食用；名称虽含“牛奶”，商品主体不是饮用奶。'],
  [/pasteis de nata/, '葡式蛋挞，是酥皮包裹蛋奶馅的烘焙甜点；可直接吃或稍微复烤，类似中国常见葡式蛋挞，不是冰淇淋。'],
  [/4 burgerboller.*6 polsebrod/, '这是 4 个汉堡面包或 6 个热狗面包二选一的促销，可夹汉堡肉、香肠或其他馅料；商品主体是面包，不是香肠。'],
  [/kyllingepopcorn/, '爆米花鸡块，是一口大小的裹粉鸡肉块；这款配甜辣蘸酱，并由熟食柜热售。可直接食用或按门店说明复热，类似中国常见盐酥鸡块，不是玉米爆米花。'],
  [/morliny.*classic.*crispy hot wings/, 'Morliny 冷冻鸡翅，有原味和香辣脆皮两种。适合烤箱或空气炸锅充分加热；这是 2 kg 大包装鸡翅，不是普通未调味鸡肉块。'],
  [/kalkunoverlaar.*schnitzel.*bryst/, '这是火鸡大腿肉或火鸡胸肉薄片二选一的促销，两者部位、带骨比例和烹调时间不同，购买时可按做法选择。'],
  [/kalkunbrystfilet/, '火鸡胸肉，脂肪较少、肉块通常比鸡胸大，可切片快炒、煎烤或做咖喱；这是火鸡肉，不是鸡胸肉。'],
  [/kalkunschnitz|kalkunstrimler/, '火鸡胸肉薄片或肉条，适合快速煎炒、做咖喱或卷饼；商品主体是火鸡胸，不是鸡胸或火鸡腿。'],
  [/kalkununderlaar/, '火鸡小腿，通常带骨且个头比鸡小腿大，肉质紧实，适合慢烤、炖煮或红烧。'],
  [/hakket kalkun/, '火鸡肉末，脂肪通常较少，可做肉丸、汉堡肉饼、饺子馅或肉酱。'],
  [/paalaegschokolade/, '丹麦面包用薄片巧克力，通常把薄巧克力片直接铺在面包上吃；不是肉类冷切。'],
  [/frugtpaalaeg|grinebidder/, '压制水果条或水果片零食，可直接食用；丹麦语 frugtpålæg 虽含 pålæg，但这里不是肉类冷切。'],
  [/rejeost|skinkeost/, '虾味或火腿味涂抹奶酪，可抹面包、饼干或做三明治；商品主体是奶酪，不是虾或火腿冷切。'],
  [/smorcroissant/, '冷冻黄油可颂，需按包装用烤箱或空气炸锅加热；“smør”表示黄油风味，但商品主体是面包。'],
  [/smorrebrod/, '丹麦开放式三明治，在一片面包上放肉、鱼、蛋或沙拉等配料，通常作为午餐直接食用；名称中的 smørrebrød 不是黄油商品。'],
  [/forarsruller|spring rolls|miniruller/, '冷冻春卷或迷你春卷，通常用烤箱、空气炸锅或油炸加热；具体馅料和加热时间以包装为准。'],
  [/asia cubes/, '冷冻亚洲风味一口小食，需加热后食用；具体馅料需按包装图片确认，不是冰淇淋。'],
];

export function danishProductNameZh(originalName, comparisonGroup) {
  const text = normalize(originalName);
  for (const [pattern, nameZh] of DANISH_PRODUCT_FORM_TITLES) if (pattern.test(text)) return nameZh;
  if (ORIGINAL_NAME_FALLBACK_GROUPS.has(comparisonGroup)) return `${originalName}（${GROUP_DEFAULTS[comparisonGroup]}）`;
  for (const [pattern, nameZh] of DANISH_TITLES) if (pattern.test(text)) return nameZh;
  return GROUP_DEFAULTS[comparisonGroup] || '商品（请核对原名）';
}

export function specificDanishDescription(originalName) {
  const text = normalize(originalName);
  for (const [pattern, descriptionZh] of SPECIFIC_DESCRIPTIONS) if (pattern.test(text)) return descriptionZh;
  return null;
}

const ENGLISH_TITLES = [
  title(/russet potatoes?/, 'Russet 褐皮土豆'), title(/sweet potatoes?.*butter/, '黄油调味红薯配菜'), title(/potatoes?/, '新鲜土豆'),
  title(/peaches?.*nectarines?|nectarines?.*peaches?/, '桃或油桃'), title(/plums?/, '李子'), title(/strawberries?/, '草莓'), title(/blueberries?/, '蓝莓'), title(/watermelon/, '西瓜'), title(/avocados?/, '牛油果'), title(/bananas?/, '香蕉'), title(/\bapples?\b/, '苹果'), title(/grapes?/, '葡萄'),
  title(/whole young chicken/, '整只嫩鸡'), title(/chicken.*(?:sub|wrap)|(?:sub|wrap).*chicken/, '鸡肉三明治或卷饼'), title(/popcorn chicken/, '爆米花鸡块'), title(/breaded chicken breasts?/, '裹粉鸡胸肉'), title(/parmesan chicken|chicken bites?/, '帕玛森裹粉鸡肉'), title(/chicken breasts?|chicken cutlets?/, '鸡胸肉'), title(/chicken thighs?|drumsticks?/, '鸡腿肉'), title(/ground chicken/, '鸡肉末'), title(/fried chicken|chicken tenders?/, '熟制或裹粉鸡肉'),
  title(/ground beef|ground chuck/, '牛肉末'), title(/beef burgers?/, '牛肉汉堡饼'), title(/ribeye|sirloin|steak/, '牛排'), title(/beef roast|chuck roast|brisket/, '整块烤牛肉'),
  title(/ground pork/, '猪肉末'), title(/pork tenderloin/, '猪里脊'), title(/pork chops?/, '猪排'), title(/pork meatballs?/, '猪肉丸'), title(/pulled pork/, '手撕猪肉'), title(/turkey bacon/, '火鸡培根'), title(/turkey breast/, '烤火鸡胸冷切'), title(/pepperoni/, '意式辣香肠片'), title(/black forest ham|\bham\b/, '火腿冷切'), title(/meat sticks?/, '肉条零食'), title(/sausage/, '香肠'), title(/bacon/, '猪肉培根'),
  title(/salmon burgers?/, '三文鱼汉堡饼'), title(/salmon|sockeye/, '三文鱼'), title(/shrimp|prawns?/, '虾'), title(/tuna.*canned|canned tuna/, '金枪鱼罐头'), title(/tuna|swordfish/, '金枪鱼或剑鱼排'),
  title(/greek yogurt/, '希腊酸奶'), title(/yogurt|yoghurt/, '酸奶'), title(/cheez-it|cheese crackers?/, 'Cheez-It 奶酪味咸饼干'), title(/cream cheese spread/, '奶油奶酪抹酱'), title(/mozzarella/, '马苏里拉奶酪'), title(/cheddar/, '切达奶酪'), title(/cheese/, '奶酪'), title(/eggs?/, '鸡蛋'),
  title(/croissants?/, '可颂'), title(/bagels?/, '贝果'), title(/bread/, '面包'), title(/cookies?/, '饼干'), title(/cake/, '蛋糕'), title(/pie/, '派'),
  title(/ice cream/, '冰淇淋'), title(/pizza/, '冷冻披萨'), title(/egg rolls?|dumplings?/, '冷冻春卷或饺子'),
  title(/rice krispies treats/, '米香棉花糖谷物棒'), title(/chips?|crisps?/, '薯片或咸味脆片'), title(/candy|chocolate/, '糖果或巧克力'),
  title(/coffee/, '咖啡'), title(/tea/, '茶'), title(/juice/, '果汁'), title(/water enhancer/, '饮水调味液'), title(/sparkling water|water/, '饮用水或气泡水'),
];

export function englishProductNameZh(originalName, comparisonGroup, groupNameZh = null) {
  const text = normalize(originalName);
  for (const [pattern, nameZh] of ENGLISH_TITLES) if (pattern.test(text)) return nameZh;
  return groupNameZh || GROUP_DEFAULTS[comparisonGroup] || '商品（请核对英文原名）';
}

const SPECIFIC_ENGLISH_DESCRIPTIONS = [
  [/popcorn chicken/, '裹粉爆米花鸡块，是一口大小的调味鸡肉小食；通常已预炸或预熟，需按包装说明用烤箱或空气炸锅复热，不是生鲜鸡肉。'],
  [/breaded chicken breasts?/, '裹粉鸡胸肉，通常已经调味并预炸或预熟；需按包装说明用烤箱或空气炸锅加热，不是未经处理的生鲜鸡胸。'],
  [/cheez-it|cheese crackers?/, '奶酪风味烘烤咸饼干，开袋即食；商品主体是脆饼，不是奶酪块或奶酪棒。'],
  [/cream cheese spread/, '冷藏奶油奶酪抹酱，质地柔软，可抹贝果或面包、做三明治或用于烘焙；不是切片或块状餐桌奶酪。'],
  [/turkey bacon/, '火鸡培根，是用火鸡肉制成的培根风格薄片，通常比猪培根更瘦；可煎脆后配早餐、三明治或沙拉，不与猪肉培根混比。'],
  [/ovengold roasted turkey breast/, '烤火鸡胸冷切肉，可直接夹三明治、卷饼或搭配沙拉；这是熟制火鸡胸切片，不是生鲜火鸡胸，也不与火腿或香肠混比。'],
  [/black forest ham/, '黑森林风味火腿冷切，通常带烟熏和咸香味，可直接夹面包、卷饼或搭配早餐；不与火鸡冷切或香肠混比。'],
  [/pepperoni/, '意式辣香肠薄片，通常用于披萨、三明治或零食拼盘；属于高盐熟制肉，不与普通鲜香肠或火腿冷切混比。'],
  [/meat sticks?/, '调味肉条零食，可直接食用；需按包装确认肉种、辣度和单条重量，不与香肠或冷切火腿混比。'],
  [/chicken.*(?:sub|wrap)|(?:sub|wrap).*chicken/, '鸡肉三明治或卷饼，是包含面包/饼皮、鸡肉和配菜的即食餐；不与单独售卖的鸡胸肉或裹粉鸡块比较最低价。'],
  [/parmesan chicken/, '帕玛森风味裹粉鸡肉块或鸡胸薄片，通常已经调味，适合烤箱或空气炸锅加热；不与生鲜鸡胸肉混比。'],
];

export function specificEnglishDescription(originalName) {
  const text = normalize(originalName);
  for (const [pattern, descriptionZh] of SPECIFIC_ENGLISH_DESCRIPTIONS) if (pattern.test(text)) return descriptionZh;
  return null;
}
